- hosts: challange-terraform-ansible
  tasks:
  - name: Instalando o python3 e virtualenv
    apt:
      pkg:
      - python3
      - python3-virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencia com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/vpc/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/vpc/venv/bin/activate; django-admin startproject setup /home/ubuntu/vpc'
  - name: Alterando os hosts do settings
    lineinfile:
      path: /home/ubuntu/vpc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
